import { DEFAULT_STATUSES } from "./config.js";

/**
 * Body scaffold for a new task: enough structure that an agent knows where to
 * write what, without forcing a rigid form onto freeform notes.
 */
export function taskBodyTemplate(title: string): string {
  return [
    `# ${title}`,
    "",
    "## Description",
    "",
    "",
    "",
    "## Acceptance criteria",
    "",
    "- [ ] ",
    "",
    "## Notes",
    "",
  ].join("\n");
}

export function configTemplate(): string {
  return `# Task manager configuration. All fields are optional.
# See \`tasks --help\` or .tasks/README.md for the full convention.

version: 1

# Default phase scope for \`tasks list\` and \`tasks ready\` (--all overrides).
# active_phase: my-phase

# Ordered status list. Commands bind to roles (below), never to these literals,
# so renaming them here is safe.
statuses:
${DEFAULT_STATUSES.map((s) => `  - ${s}`).join("\n")}

# Roles default to the first / second / last entries of \`statuses\`.
# roles:
#   ready: ${DEFAULT_STATUSES[0]}
#   claimed: ${DEFAULT_STATUSES[1]}
#   done: ${DEFAULT_STATUSES[2]}

# Explicit transition pairs. Omit to use the default rule: step forward or back
# by exactly one status. Providing this REPLACES the default rule entirely.
# transitions:
#   - [${DEFAULT_STATUSES[0]}, ${DEFAULT_STATUSES[1]}]
#   - [${DEFAULT_STATUSES[1]}, ${DEFAULT_STATUSES[0]}]
#   - [${DEFAULT_STATUSES[1]}, ${DEFAULT_STATUSES[2]}]
#   - [${DEFAULT_STATUSES[2]}, ${DEFAULT_STATUSES[1]}]
`;
}

export function gitignoreTemplate(): string {
  return `# Transient lock files — never committed.
.locks/
`;
}

/** Agent-facing convention doc: where a cold agent learns the tool exists. */
export function readmeTemplate(): string {
  return `# Tasks

This directory is a local, git-versioned task tracker. It is managed by the
\`tasks\` CLI. Task files are plain markdown and safe to read directly; prefer
the CLI for any change, because it enforces the rules below.

## Layout

\`\`\`
.tasks/
  config.yml      project config (statuses, roles, active_phase)
  README.md       this file
  _index.md       generated overview — regenerate with \`tasks reindex\`
  <phase>/        a phase directory, e.g. auth-rework/ or 2026-q1/
    <id>.md       one task
  .archive/       soft-deleted tasks, excluded from all default queries
\`\`\`

## For an agent starting work

\`\`\`sh
tasks ready --json       # what is unblocked right now
tasks claim <id>         # take it (fails if someone already has it)
# ...do the work...
tasks status <id> DONE   # complete it
\`\`\`

Every read command accepts \`--json\`. Errors are JSON on stderr under
\`--json\`, and exit codes are meaningful: 0 success, 2 usage, 3 not found,
4 state conflict. Branch on the exit code, not on message text.

## Rules the CLI enforces

- **Status transitions.** By default a task moves forward or back exactly one
  status at a time, so nothing jumps straight to done without being worked.
- **Dependencies.** \`depends_on\` lists task ids. A task is only "ready" when
  every dependency is done. Missing, archived, and cyclic dependencies all
  count as blocking, never as satisfied.
- **Ids are globally unique** across this directory, including \`.archive/\`.
- **The directory owns a task's phase**; use \`tasks move\` rather than \`mv\`.

## Frontmatter

The YAML block at the top of each task is machine-owned — the CLI rewrites it
in canonical form and does not preserve comments there. The markdown body below
it is yours: edit it freely. If frontmatter is hand-edited into an inconsistent
state, \`tasks validate\` reports it and \`tasks validate --fix\` repairs the
mechanically safe parts.
`;
}

export function indexTemplate(sections: string): string {
  return `<!-- Generated by \`tasks reindex\`. Do not edit by hand. -->

# Task index

${sections}`;
}
